### ISSUE TITLE
Getting "lsetxattr com.apple.provenance /oci-layout: operation not supported" on a mac

### ISSUE THREAD

**Issue by jeffsaremi** [gdraheim/docker-copyedit#21]
Not sure if I'm doing something wrong or is this supported on a mac?

```
❯ ./docker-copyedit.py FROM golang:latest INTO golang2 -vv -T /tmp set label "userid" "0:0"
WARNING:edit:output image is local (None)
INFO:edit:new /tmp/data from docker save
WARNING:edit:done  new label 'userid' 0:0
INFO:edit:written new /tmp/data/8c5b2ffbe44aa2888737f1696530a0558c4e6c2fbf913059167772fd3ea5fede.json
INFO:edit:removed old /tmp/data/blobs/sha256/98ef6bdf40ba9a262cb121fff28759f9431fe888655704c97a65aae643defd77
ERROR:edit:CMD docker load -i /tmp/ready.tar
ERROR:edit:EXIT 1
ERROR:edit:STDOUT b''
ERROR:edit:STDERR b'lsetxattr com.apple.provenance /oci-layout: operation not supported\n'
Traceback (most recent call last):
  File "/Users/jeffsaremi/src/docker-copyedit/./docker-copyedit.py", line 976, in <module>
    sys.exit(run(*args))
  File "/Users/jeffsaremi/src/docker-copyedit/./docker-copyedit.py", line 905, in run
    return edit_image(inp, out, commands)
  File "/Users/jeffsaremi/src/docker-copyedit/./docker-copyedit.py", line 331, in edit_image
    sh(cmd.format(**locals()))
  File "/Users/jeffsaremi/src/docker-copyedit/./docker-copyedit.py", line 73, in sh
    raise ShellException("shell command failed", result)
__main__.ShellException: shell command failed
```

**Comment by gdraheim** [comment]
https://github.com/moby/moby/issues/47517
this is related to a bug-fix where previously failures on applying extended-attributes were silently ignored, which in some cases could result to an image that was silently broken (due to those attributes getting lost in the process). The expectation for docker load from a tarball is to restore the filesystem from the tarball, including attributes set on the file. In this case, the generated tarbal contains extended-attributes that are specific to macOS, and that cannot be applied to Linux filesystems (causing an error to be produced). Admitted, handling of extended attributes is not well-defined in the OCI image specification (there's some discussion ongoing in this area to have a better definition).

https://docs.docker.com/engine/release-notes/26.0/
Fix ADD Dockerfile instruction failing with lsetxattr <file>: operation not supported when unpacking archive with xattrs onto a filesystem that doesn't support them. [moby/moby#47175](https://github.com/moby/moby/pull/47175)

https://github.com/moby/moby/issues/47962
Starting with v25, docker will no longer silently remove extended attributes when unpacking layers, and will instead fail (see [v25.0 release notes](https://github.com/moby/moby/releases/tag/v25.0.0) and https://github.com/moby/moby/pull/45464)

=> you probably need to update the docker engine?

**Comment by gdraheim** [comment]
btw, works for me on a pre-25 version

    > ./docker-copyedit.py FROM golang:latest INTO golang2 -vv -T /tmp set label "userid" "0:0"
    WARNING:edit:output image is local (None)
    INFO:edit:new /tmp/data from docker save
    WARNING:edit:done  new label 'userid' 0:0
    INFO:edit:written new /tmp/data/9b7dd368d0914bd3b8a9015bc991db1f614ff4eb3a3a857408d38ba9a986d449.json
    INFO:edit:removed old /tmp/data/a61b645b609b758e4c0a9c57efbba8ccc610abb4d96544cedd8411aa1c9e4b09.json
    > docker --version
    Docker version 24.0.7-ce, build 311b9ff0aa93

**Comment by jeffsaremi** [comment]
Just upgraded to 27. It works like a charm now
Prior to add I also got it to work by using `gnu-tar` and supplying with an `no-xattr` flag
Thanks for your help
